// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/gpt/gpt.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/gpt/gpt.go -destination=internal/app/gpt/gpt_mock.go -package=gpt
//

// Package gpt is a generated GoMock package.
package gpt

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FetchChangelog mocks base method.
func (m *MockClient) FetchChangelog(ctx context.Context, commits string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchChangelog", ctx, commits)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchChangelog indicates an expected call of FetchChangelog.
func (mr *MockClientMockRecorder) FetchChangelog(ctx, commits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchChangelog", reflect.TypeOf((*MockClient)(nil).FetchChangelog), ctx, commits)
}

// FetchCommitMessage mocks base method.
func (m *MockClient) FetchCommitMessage(ctx context.Context, diff string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCommitMessage", ctx, diff)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCommitMessage indicates an expected call of FetchCommitMessage.
func (mr *MockClientMockRecorder) FetchCommitMessage(ctx, diff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCommitMessage", reflect.TypeOf((*MockClient)(nil).FetchCommitMessage), ctx, diff)
}
