linters:
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    # - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
  fast: false
  disable-all: true

issues:
  exclude-dirs:
    - docs
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
