comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no

coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project:
      default:
        threshold: 1.0
        target: 70%
    patch:
      default:
        threshold: 1.0
        target: 70%

ignore:
  - "**/*_mock.go"
  - "**/*_test.go"
  - "**/module.go"
