// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/cli/workflow/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/cli/workflow/service.go -destination=internal/app/changelog/workflow_mock_test.go -package=changelog
//

// Package changelog is a generated GoMock package.
package changelog

import (
	workflow "cmt/internal/app/cli/workflow"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GenerateChangelog mocks base method.
func (m *MockService) GenerateChangelog(ctx context.Context, between string) (workflow.ChangelogResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateChangelog", ctx, between)
	ret0, _ := ret[0].(workflow.ChangelogResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateChangelog indicates an expected call of GenerateChangelog.
func (mr *MockServiceMockRecorder) GenerateChangelog(ctx, between any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateChangelog", reflect.TypeOf((*MockService)(nil).GenerateChangelog), ctx, between)
}

// GenerateCommit mocks base method.
func (m *MockService) GenerateCommit(ctx context.Context, prefix string) (workflow.CommitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCommit", ctx, prefix)
	ret0, _ := ret[0].(workflow.CommitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCommit indicates an expected call of GenerateCommit.
func (mr *MockServiceMockRecorder) GenerateCommit(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCommit", reflect.TypeOf((*MockService)(nil).GenerateCommit), ctx, prefix)
}
