name: Master
on:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency:
  group: master
  cancel-in-progress: true
jobs:
  coverage:
    name: Codecov
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        # NOTE: https://github.com/codecov/codecov-action/releases/v5.4.3
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
