name: Master
on:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency:
  group: master
  cancel-in-progress: true
jobs:
  coverage:
    name: Codecov
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        # NOTE: https://github.com/codecov/codecov-action/releases/v5.3.1
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
