name: Master
on:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency:
  group: master
  cancel-in-progress: true
jobs:
  coverage:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
